"""added followers auxiliary table

Revision ID: 415a4c1eed38
Revises: 85dc15ba85e4
Create Date: 2021-07-08 15:40:01.229763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415a4c1eed38'
down_revision = '85dc15ba85e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
